name: json_isolate_parser
description: Parse JSON in isolates with generics and seamless Dio integration.
version: 0.0.2
homepage: https://github.com/StefanKostovski991
repository: https://github.com/StefanKostovski991/json_isolate_parser


environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.5.0
  meta: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0
